version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "deploytheback"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1suq4pn6g43zc"
s3_prefix = "deploytheback"
region = "ap-south-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
